- name: "Load MYSQL variables"
  ansible.builtin.include_vars: mysql.vars.ansible.yaml

- name: "Install dependencies"
  ansible.builtin.apt:
    update_cache: true
    force: true
    state: present
    name:
      - software-properties-common
      - python3-pymysql

- name: "Install MariaDB"
  ansible.builtin.apt:
    update_cache: true
    force: true
    state: present
    name: mariadb-server

- name: "Create MariaDB database"
  community.mysql.mysql_db:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_db }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: "Create MariaDB user"
  community.mysql.mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_privileges }}"
    state: present
